CREATE TABLE IF NOT EXISTS products (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT        NOT NULL,
  brand       TEXT        NOT NULL,
  price       INTEGER     NOT NULL CHECK (price >= 0),
  storage     INTEGER     NOT NULL,              -- GB
  ram         INTEGER     NOT NULL,              -- GB
  color       TEXT        NOT NULL DEFAULT '',
  processor   TEXT        NOT NULL DEFAULT '',
  camera      TEXT        NOT NULL DEFAULT '',
  battery     TEXT        NOT NULL DEFAULT '',
  description TEXT        NOT NULL DEFAULT '',
  image       TEXT        NOT NULL DEFAULT '',
  stock       INTEGER     NOT NULL DEFAULT 0 CHECK (stock >= 0),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
  customer_name TEXT        NOT NULL,
  phone         TEXT        NOT NULL,
  address       TEXT        NOT NULL,
  comment       TEXT        NOT NULL DEFAULT '',
  total_price   INTEGER     NOT NULL,
  status        TEXT        NOT NULL DEFAULT 'new',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- product_name хранит название на момент заказа: телефон можно удалить, история останется
CREATE TABLE IF NOT EXISTS order_items (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id     INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id   INTEGER REFERENCES products(id) ON DELETE SET NULL,
  product_name TEXT    NOT NULL,
  quantity     INTEGER NOT NULL CHECK (quantity > 0),
  price        INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand);
CREATE INDEX IF NOT EXISTS idx_products_price ON products(price);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);

-- Настройки магазина (контакты для кнопки «Связаться»)
CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT ''
);

-- Доставка и оплата (добавлено позже; IF NOT EXISTS делает скрипт безопасным для существующей базы)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_method TEXT NOT NULL DEFAULT 'courier';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_price  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method  TEXT NOT NULL DEFAULT 'cash';   -- card | cash
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status  TEXT NOT NULL DEFAULT 'unpaid'; -- unpaid | pending | paid | failed
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_id      TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at         TIMESTAMPTZ;
-- секретный ключ из ссылки, по которой покупатель видит свой заказ без входа
ALTER TABLE orders ADD COLUMN IF NOT EXISTS access_key      TEXT;

-- Аксессуары живут в той же таблице, что и телефоны: общие корзина, заказы и остатки.
-- kind: phone | accessory;  category — категория аксессуара (у телефонов пустая)
ALTER TABLE products ADD COLUMN IF NOT EXISTS kind     TEXT NOT NULL DEFAULT 'phone';
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '';
ALTER TABLE products ALTER COLUMN storage SET DEFAULT 0;
ALTER TABLE products ALTER COLUMN ram SET DEFAULT 0;
ALTER TABLE products ALTER COLUMN brand SET DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_products_kind ON products(kind);

-- Загруженные фото, когда сервер работает с облачной базой (на Render и Vercel диск не сохраняется)
CREATE TABLE IF NOT EXISTS images (
  id         TEXT PRIMARY KEY,
  mime       TEXT NOT NULL,
  data       BYTEA NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
